### ISSUE TITLE
Services bullet points issue

### ISSUE THREAD

**Issue by Cupofassam** [rehive/rehive-static-site#19]
Hey AQ,

Not sure why but the yellow bullet points on the Services page have gone a bit weird.

https://rehive.com/services/

What they used to look like:

![image](https://user-images.githubusercontent.com/22153546/37608245-b87b730a-2ba2-11e8-9e4c-f863b92443dd.png)

What they look like now:

![image](https://user-images.githubusercontent.com/22153546/37608261-c4cf5d2e-2ba2-11e8-9640-4a33fe0cb07a.png)

Please fix, thanks

**Comment by AquiburRKhan** [comment]
Found a better solution while fixing this issue , so also implemented it in the platform lists, so also test out https://rehive.com/platform/  bullet points please :)
