### ISSUE TITLE
Hives in Rehive logo aren't clickable on 4k screen

### ISSUE THREAD

**Issue by Cupofassam** [rehive/rehive-static-site#23]
Hey AQ

On my 4k screen I can't click the hives in the Rehive logo:

https://drive.google.com/file/d/1GDfsQAYBXkBJwtZMS-gMJc6IxTugEXgY/view

**Comment by AquiburRKhan** [comment]
This issue is happening because of the header options div overlapping the rehive icon, I fixed it somewhat , But It can will be fixed better after merging issue10

**Comment by Cupofassam** [comment]
👍
