### ISSUE TITLE
Fix pages with old styling

### ISSUE THREAD

**Issue by ConnorMac** [rehive/rehive-static-site#50]
- [x] https://staging.rehive.com/technology/
- [x] https://staging.rehive.com/services/

**Comment by michailbrynard** [comment]
The above two will be completely removed.
- [ ] https://staging.rehive.com/contact/

**Comment by michailbrynard** [comment]
- [ ] https://staging.rehive.com/join-slack/

**Comment by Stephan-e** [comment]
I did rework the older sites that are part of the new site. 
did not do /technology and /services

**Comment by OdinsPlasmaRifle** [comment]
Are  /technology and /services going to be used in future? If not, it might be worth deleting the pages?

**Comment by Stephan-e** [comment]
It wasn't in the original doc helghardt made, and no mention of it. 
I can remove the pages if we aren't going to use them

**Comment by michailbrynard** [comment]
I think we've covered most of the old styling I can spot, so closing this issue for now.
