### ISSUE TITLE
Mobile hamburger menu clickability.

### ISSUE THREAD

**Issue by michailbrynard** [rehive/rehive-static-site#51]
Mobile hamburger menu seems to only activate when one clicks exactly on the icon lines. Would be better if the entire icon area triggers the menu.

**Comment by OdinsPlasmaRifle** [comment]
I think this is fairly important and may actually result in fixing this: #55 

@Stephan-e should I ask Taariq to take a look at navbar again?

**Comment by Stephan-e** [comment]
Yeah it might be better if he looks into it.

**Comment by michailbrynard** [comment]
Thanks @TarCode , the menu is now much more clickable on my phone.

@Stephan-e, one thing I noticed is the "Events" and "Community" links on the mobile menu are old and can be removed. After that I think we can close this issue.

**Comment by Stephan-e** [comment]
okay cool, its done
