### ISSUE TITLE
landing page updates phase 2

### ISSUE THREAD

**Issue by Stephan-e** [rehive/rehive-static-site#54]
nina has different arrows to be used on pages for links like "sign up" and "read more"

**Comment by ninadewaal** [comment]
![design feedback- home](https://user-images.githubusercontent.com/35197761/46367491-052fd580-c67e-11e8-8cbf-c9af6accfb12.png)

**Comment by michailbrynard** [comment]
I think this has been superseded by #69 and other issues.
