### ISSUE TITLE
Navbar Menu doesn’t work on my phone

### ISSUE THREAD

**Issue by michailbrynard** [rehive/rehive-static-site#55]
On the new-site branch the navbar menu button is way less responsive than on the current rehive site when testing on my phone. I often need to click 3 times to get the menu to pop up.

**Comment by Stephan-e** [comment]
I am struggling to replicate this issue. works fine on my mobile, maybe i should try using safari.

**Comment by michailbrynard** [comment]
Hmmm, I have the issue in both chrome and safari on iphone, but as Josh mentioned I think it is related to # 51.  I'll close this one for now, let's move discussion to the other issue.
