### ISSUE TITLE
Homepage layout issues

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/rehive-static-site#56]
### NB: This does not have to be acted upon immediately we can plan out priorities on Monday when everyone has had a chance to provide feedback.

This is to address layout issues on the homepage. These are not "law" but they should at least be discussed. I will defer to Nina if it comes down to a "design discussion".

**Homepage hero image**

The positioning of the hero image seems too far right and down.

![homepage](https://user-images.githubusercontent.com/13023194/46527268-fff6a480-c890-11e8-8c9e-9d24f12ed64c.png)

**Homepage hero image spacing**

The spacing between the hero text and the next piece of content is extremely large. Feels unnatural. I think it should be reduced by almost half.

![homepage2](https://user-images.githubusercontent.com/13023194/46527288-0ab13980-c891-11e8-947f-909b08b48249.png)

**Homepage section spacing**

The space on the left looks like it is missing a graphic or something? the spacing between each section makes the page feels somewhat disjointed.

![homepage3](https://user-images.githubusercontent.com/13023194/46527302-17359200-c891-11e8-843a-eeaa25fa0178.png)

**Homepage blue box**

I suggest a simple spacing reduction again. But I am not set in stone on this one at all.

![homepage4](https://user-images.githubusercontent.com/13023194/46527349-3fbd8c00-c891-11e8-826b-db4727078d6d.png)

**Homepage features products**

the graphic should not be cut off. The spacing between sections and "section content" should be consistent. The 4 "featured products" should be centered like the title is centered. or the boxes should be increased in width so they are just seem centered.

![homepage5](https://user-images.githubusercontent.com/13023194/46527366-4a782100-c891-11e8-9111-54071a9c0336.png)

**Comment by michailbrynard** [comment]
<img width="1095" alt="screen shot 2018-10-09 at 3 36 42 pm" src="https://user-images.githubusercontent.com/7025263/46673889-242ceb00-cbdb-11e8-9a87-e1ffcec0c5f4.png">
These images suddenly don't seem equally sized.

**Comment by Stephan-e** [comment]
- Layout padding has been reduced on large screens due to switching to rem padding opposed to percentage padding. 
- Banner with cubes was a struggle to prevent clipping, I made two images one for normal and one for larger screens 
- changed social icons to same size. 
- centered boxes in products

**Comment by michailbrynard** [comment]
How did some of the content change again?
E.g. I see 
"Easily distribute tokens to your community for completing actions that are important to **you** business."

I remember fixing this here:
https://github.com/rehive/rehive-static-site/commit/139e0ab5677e203480345d55611bf94d2c57fdc4#diff-1578c58a761c0846adb0e788c860a12bL208

**Comment by Stephan-e** [comment]
It must have been a merge issue I had last week, sorry about that. I changed the content back to how yours was.

**Comment by OdinsPlasmaRifle** [comment]
The bugs reported in this issue seem to have been resolved.

There are several other issues that have popped up but will report those in a separate bug.
