### ISSUE TITLE
Bussiness page layout issues

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/rehive-static-site#57]
### NB: This does not have to be acted upon immediately we can plan out priorities on Monday when everyone has had a chance to provide feedback.

This is to address layout issues on the business page. These are not "law" but they should at least be discussed. I will defer to Nina if it comes down to a "design discussion".

**Business page first section**

title alignment is off.

![business](https://user-images.githubusercontent.com/13023194/46528703-bd36cb80-c894-11e8-9f9a-9914c0ba318e.png)

**Business page for business**

Alignment needs adjusting.

![business2](https://user-images.githubusercontent.com/13023194/46528811-f5d6a500-c894-11e8-8b15-05ca631afac6.png)

**Business page consulting**

Alignment needs adjusting.

![business3](https://user-images.githubusercontent.com/13023194/46528807-f40ce180-c894-11e8-8f1d-fa07ac0dec34.png)

**Business page footer**

Footer spacing is massive. Maybe a minor  reduction?

![business4](https://user-images.githubusercontent.com/13023194/46528804-f1aa8780-c894-11e8-9372-d9ddc7838e6c.png)

**Comment by Stephan-e** [comment]
- sorted out most of the alignment issues and content should now be aligned.
- spacing fixed with rem padding

**Comment by OdinsPlasmaRifle** [comment]
This is completed!
