### ISSUE TITLE
Platform page layout issues

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/rehive-static-site#58]
### NB: This does not have to be acted upon immediately we can plan out priorities on Monday when everyone has had a chance to provide feedback.

This is to address layout issues on the business page. These are not "law" but they should at least be discussed. I will defer to Nina if it comes down to a "design discussion".

**Hero  title text position**

Text is outside of its container.

![platform](https://user-images.githubusercontent.com/13023194/46529141-eefc6200-c895-11e8-9a53-2555440b9518.png)

It seems like the platform page has consistent alignment and positioning of titles and sub content. which is good.

However, one comment I have regarding the page in general is that there is a lot of "open" space. It makes the page feel very sparse. 

a couple options:

1. reduce "whitespace" between items. But the amount of white space may be intentional?
2. Increase text size on some elements
3. Add some graphics here and there.

I would suggest some general reduction in spacing would be good. but nothing extreme.

**Comment by Stephan-e** [comment]
- standardised image sizes on all the hero banners
- aligned text on all the hero banners
- reduction in whitespace should be better to new padding
- partners in mobile goes underneath each other now. 
- aligned content as with other pages

**Comment by OdinsPlasmaRifle** [comment]
Alignment issues reported and other problems addressed. closing this.
