### ISSUE TITLE
Wallet page layout issues

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/rehive-static-site#59]
### NB: This does not have to be acted upon immediately we can plan out priorities on Monday when everyone has had a chance to provide feedback.

This is to address layout issues on the wallet page. These are not "law" but they should at least be discussed. I will defer to Nina if it comes down to a "design discussion".

**Hero image**

The hero image is an odd choice.

![wallet](https://user-images.githubusercontent.com/13023194/46530103-038e2980-c899-11e8-8afc-40eb3b342e9b.png)

**Mobile phone example**

The "whole" element feels slightly off center

![wallet2](https://user-images.githubusercontent.com/13023194/46530123-1274dc00-c899-11e8-8d71-b4f5ca9f34c3.png)

**For your business section**

Small alignment issues

![wallet3](https://user-images.githubusercontent.com/13023194/46530164-26b8d900-c899-11e8-8ed2-0f79f2ac0f12.png)

**Grow your business section**

Alignment needs to be reviewed.

![wallet4](https://user-images.githubusercontent.com/13023194/46530196-3b956c80-c899-11e8-926f-0e345a139df2.png)

**Comment by Stephan-e** [comment]
- used standard hero image size and heading as other pages
- padding and whitespace resolved as other pages
- aligned content in pages
- centered the elements around the demo phone and added an image.

**Comment by michailbrynard** [comment]
The hero image and text size and alignment seems off compared to the Platform and Stellar pages.

**Comment by michailbrynard** [comment]
Is this the actual mobile app? Or the webapp?

In this promotional image, we shouldn't use cards that seem weird like "Welcome to Default." If the cards are too generic, maybe switch to the transaction view instead.

<img width="337" alt="screen shot 2018-10-10 at 12 27 36 pm" src="https://user-images.githubusercontent.com/7025263/46730378-4466b380-cc88-11e8-8d3f-e89c9d8bdbe8.png">

**Comment by Stephan-e** [comment]
I found the bug and fixed the wallet page header in new commit
will change the text of the wallet screen

**Comment by michailbrynard** [comment]
Thanks, looks much better, but it still seems when clicking between platform and wallet, the wallet text is a "Wallet, rewards and perks" text is lower than "Powerful transactional management system" text.

**Comment by Stephan-e** [comment]
yeah i finally found the padding issue, it wasn't on this page but rather the other pages. but did commit a fix now

**Comment by OdinsPlasmaRifle** [comment]
The issues reported here have been resolved.
