### ISSUE TITLE
Stellar page layout issues

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/rehive-static-site#60]
### NB: This does not have to be acted upon immediately we can plan out priorities on Monday when everyone has had a chance to provide feedback.

This is to address layout issues on the stellar page. These are not "law" but they should at least be discussed. I will defer to Nina if it comes down to a "design discussion".

**Features section**

Alignment, spacing and positioning issues.

![stellar](https://user-images.githubusercontent.com/13023194/46530545-6207d780-c89a-11e8-8763-7ab96e10095e.png)

**Comment by Stephan-e** [comment]
- implemented standard hero text and image, alignment, spacing as with other pages. 
- changed the cards and images as requested above.

**Comment by OdinsPlasmaRifle** [comment]
This is much better, thank you
