### ISSUE TITLE
General page layout issues

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/rehive-static-site#61]
### NB: This does not have to be acted upon immediately we can plan out priorities on Monday when everyone has had a chance to provide feedback.

This is to address general layout issues on the website These are not "law" but they should at least be discussed. I will defer to Nina if it comes down to a "design discussion".

**Hero sections (banner area)**

Graphic - The way the graphic is included seems to vary. Sometimes it flows out of the main website container and sometimes it is forced into the container (ie`/stellar/`).

Text - The main text and sub text seems to sometimes use 2 different colors and sometimes the same colors.

**Content sections**

Spacing - on average I feel like the spacing and padding is too much. There are large swathes of unused space. This is fine from a design perspective, but we must at least make the spacing consistent between different sections and the contents within those sections.

The footer in particular has too much space between it and the content IMHO.

**Container overflow**

There are a couple places where content is still existing the "general width" of the page. For example the "terms of use" page and the "about" page.

**Menu navigation**

The "Sign in" button seems to overflow more to the right than any content on the site. This may be related to the above point in some way.

**Text colors**

The text seems to switch between 2 shades of black even in elements with similar structure elsewhere.

I think we must just clarify when the 1 shade should be used and when the other should be used.

**Buttons**

We seems to switch between a couple different button colors and types.

For example the "contact" page button seems completely different to the others (and the hover effect seems to be in reverse).

**Team photos**

I do not like the stagger design personally and I don;t think the shape of the images is working well. (Side note there is also some weird spacing between "titles" and sections here.

**Comment by Stephan-e** [comment]
Hero sections :
- standardised image size and text on all relevant pages
- changed all the font colors in css to be consistent

Content sections:
- resolved most of the spacing issues

Container overflow:
- put the terms of use and some pricing elements in containers

Menu navigation:
- tried to align sign in page, might not be 100% yet

Text colors:
- tried to keep consistent colour use, might need to be reviewed 

Buttons: 
- changed the outstanding buttons to the new theme

Team Photos: 
- changed it back to the circle picture instead of the boxes,

**Comment by OdinsPlasmaRifle** [comment]
Most of these issues seem to be resolved, we can open new issues if anything comes up again.
