### ISSUE TITLE
Add tracking

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/rehive-static-site#63]

**Comment by michailbrynard** [comment]
From the brief slack discussion, the main things we want to track are:
1. Page views, drop-offs, behaviour flow etc.
2. Company registrations
3. User registrations
4. Active companies and active users

We are already tracking (1) via the Google Analytics javascript we currently have running.

As next steps for minimum viable analytics on the static website, we'll add google analytics events to all the main call to actions:
- Get started
- Sign in
- Join our slack community
- Contact

Also look at tracking of outgoing links, e.g. to our Documentation, Github, Medium blog etc.

**Comment by michailbrynard** [comment]
Google Analytics does support cross domain tracking, we'd just need to add the google analytics js to dashboard and wallet and then add a query parameter to all our links to those sites:
`<a href="https://destination.com/?clientId=XXXXXX">destination.com</a>`
https://developers.google.com/analytics/devguides/collection/analyticsjs/cross-domain

For now I'm going with the button/link event tracking.

**Comment by michailbrynard** [comment]
Added PR https://github.com/rehive/rehive-static-site/pull/66

This also looks worth looking into for making event management easier: https://developers.google.com/tag-manager/quickstart

"Google Tag Manager"

**Comment by michailbrynard** [comment]
Closing for now.
