### ISSUE TITLE
About Page - portraits not sitting right on all screen sizes

### ISSUE THREAD

**Issue by Cupofassam** [rehive/rehive-static-site#7]
Hey AQ,
On my screen the portraits are not sitting correctly

![image](https://user-images.githubusercontent.com/22153546/37517013-d1fadf6e-2918-11e8-8624-680c9cc19111.png)

This is in Chrome and my resolution is 3840 x 2160 at 300% scaling

**Comment by AquiburRKhan** [comment]
`3840 x 2160` thats a huge monitor you have, but I can only replicate this in smaller resolutions more specifically between 1350px and 995px , in my biggest monitor which is 1861x745 its working properly
